### ISSUE TITLE
Improve urls of subpages of the pycompwa website

### ISSUE THREAD

**Issue by redeboer** [ComPWA/pycompwa#69]
Currently, some urls of our website, contain an underscore, like so:

* https://compwa.github.io/_api/pycompwa.html
* https://compwa.github.io/_examples/Quickstart.html

This is only case for pages that have been included through a [`toctree`](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-toctree).

The underscores were added to render the pages correctly through the [GitHub Pages repo](https://github.com/ComPWA/ComPWA.github.io). It could be, however, that this is no longer necessary,  [now that we make use of the `githubpages` Sphinx extension](https://github.com/ComPWA/pycompwa/commit/2a4a58ca69753bfde99f3409ab23e971b1252fa0#diff-555c472a89566734e0d8567fb205d5dfR70).

**Comment by redeboer** [comment]
Related to https://github.com/ComPWA/pycompwa/issues/69

**Comment by spflueger** [comment]
What is it related to, 70?
I cannot say for sure but it seems like if the `.nojekyll` file is present, this those underscore can be removed. Best to try it out in some test repo (build new docs locally and push)

**Comment by redeboer** [comment]
> What is it related to, 70?

Yep, sorry

**Comment by redeboer** [comment]
Yeah although we could also just try and revert if it fails. The fix itself is simple.
> Best to try it out in some test repo (build new docs locally and push)

**Comment by spflueger** [comment]
Its actually faster if you try it out locally and push it because you dont have to wait for CI
So do this:
1. create a github pages branch on some repo and activate this in the settings
2. build the pycompwa docs locally
3. push the build to that github pages branch
4. check the results

**Comment by redeboer** [comment]
Ah ok, will do
