### ISSUE TITLE
Split Quickstart into separate workflow step notebooks

### ISSUE THREAD

**Issue by redeboer** [ComPWA/pycompwa#70]
The [Quickstart notebook](https://github.com/ComPWA/pycompwa/blob/bf11102/examples/jupyter/Quickstart.ipynb) consists of a few steps (create model, generate data, perform fit, visualize), but you always have to run the notebook as a whole. In practice, however, you want to work with separate notebooks/python scripts for each of those steps. For instance, you don't want to have to rerun your fit after visualization. 

So, splitting up the Quickstart into 'workflow' notebooks would have a few advantages:

* The underlying notebooks can be downloaded and easily adapted to one's own analysis.
* Each step would illustrate how to export results and import the output of the previous step.
* On the [examples page](https://compwa.github.io/examples.html), the workflow would become separate pages that you can step through.
* The rendered examples pages are easier to glance over and clearly illustrate each aspect of ComPWA (and can as such be referred to elsewhere in the document).

Related:
* Would close https://github.com/ComPWA/pycompwa/issues/7
* Would close https://github.com/ComPWA/pycompwa/issues/32
* Related to https://github.com/ComPWA/pycompwa/issues/13

**Comment by redeboer** [comment]
Would close https://github.com/ComPWA/pycompwa/issues/32

**Comment by redeboer** [comment]
Related to https://github.com/ComPWA/pycompwa/issues/13

**Comment by redeboer** [comment]
Would close https://github.com/ComPWA/pycompwa/issues/7

**Comment by spflueger** [comment]
I like the idea! It might still be nice to have some reduced quickstart example, that showcases the most important features quickly and points to different sections for more details
